name: CI
on:
  push:
    branches: main #develop向けのプルリクが作成されたときにジョブを実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #チェックアウトするアクション
      - name: Use NodeJS
        uses: actions/setup-node@v1 #特定バージョンのnodeを設定するアクション
        with:
          node-version: "12.x"
          
      - name: npm install
      run: npm install
      - name: deploy to GitHub Pages
      working-directory: ./src
      run: npm run build